/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 toy1.gltf
Author: yanix (https://sketchfab.com/yanix)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plush-toy-304f877357de42a6a018b1d96fa571af
Title: Plush toy
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export default function Toy(props) {
  // const meshRef = useRef(null);
  // useFrame(() => (meshRef.current.rotation.z += 0.003));
  const { nodes, materials } = useGLTF('/plush_toy/toy1.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane_0.geometry} material={materials.bear} position={[-0.11, 0.28, -0.07]} />
        <mesh geometry={nodes.Cube_0.geometry} material={materials.material} position={[0.69, -0.85, 4.11]} rotation={[Math.PI / 2, 0.33, 0]} scale={0.27} />
        <mesh geometry={nodes.Cube001_0.geometry} material={materials.material} position={[-0.78, -0.82, 4.11]} rotation={[Math.PI / 2, -0.3, 0]} scale={0.27} />
        <mesh geometry={nodes.Cube002_0.geometry} material={materials.nose} position={[0.07, -1.75, 4.12]} rotation={[0, 0.09, 0.02]} scale={[0.12, 0.11, 0.11]} />
        <mesh geometry={nodes.Cylinder011_0.geometry} material={materials.glass} position={[-0.11, 0.28, -0.07]} />
      </group>
    </group>
  )
}

useGLTF.preload('/plush_toy/toy1.gltf')
