/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 model.gltf
Author: Cap Arts (https://sketchfab.com/caparts)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/huggy-toy-c3b1b0d57f424c01909f1e150541ae95
Title: Huggy toy
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Toy(props) {
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.gltf')
